// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again
// with `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types, depend_on_referenced_packages
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'
    as obx_int; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart' as obx;
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import 'data/objectbox/entities.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <obx_int.ModelEntity>[
  obx_int.ModelEntity(
    id: const obx_int.IdUid(1, 3336502618017039330),
    name: 'ChatMemberEntity',
    lastPropertyId: const obx_int.IdUid(13, 592346669483888533),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 1494575237865388267),
        name: 'obxId',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 5973769375680191063),
        name: 'uid',
        type: 9,
        flags: 2080,
        indexId: const obx_int.IdUid(1, 4129028886190630067),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 3268550594354436807),
        name: 'chatRoomId',
        type: 9,
        flags: 2048,
        indexId: const obx_int.IdUid(2, 26288467914636214),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 5636871450461295256),
        name: 'accountId',
        type: 9,
        flags: 2048,
        indexId: const obx_int.IdUid(3, 6566834307981645084),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 8393976247928908746),
        name: 'accountJson',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 7752192006140523491),
        name: 'nick',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 8538108031225961312),
        name: 'notify',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(8, 7496142961581840841),
        name: 'joinedAtMs',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(9, 8003548019459805278),
        name: 'breakUntilMs',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(10, 4529485294080339338),
        name: 'timeoutUntilMs',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(11, 4100478643467360306),
        name: 'createdAtMs',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(12, 7778778575627072234),
        name: 'updatedAtMs',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(13, 592346669483888533),
        name: 'deletedAtMs',
        type: 6,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(2, 7468620651290787438),
    name: 'ChatMessageEntity',
    lastPropertyId: const obx_int.IdUid(22, 9196135481494364333),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 483933471655412656),
        name: 'obxId',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 6134427489469217529),
        name: 'uid',
        type: 9,
        flags: 2080,
        indexId: const obx_int.IdUid(4, 3939498767496357674),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 5964111958790264553),
        name: 'roomId',
        type: 9,
        flags: 2048,
        indexId: const obx_int.IdUid(5, 4375267654533302047),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 7063999759174650398),
        name: 'senderId',
        type: 9,
        flags: 2048,
        indexId: const obx_int.IdUid(6, 1924873232890338477),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 9154022089063598045),
        name: 'content',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 6023106371676765431),
        name: 'dataJson',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(8, 7982091411147176206),
        name: 'createdAtMs',
        type: 6,
        flags: 8,
        indexId: const obx_int.IdUid(7, 7091517885592619742),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(9, 1305421133564644732),
        name: 'status',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(10, 1062737535444990846),
        name: 'isDeleted',
        type: 1,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(11, 6446559177340633045),
        name: 'updatedAtMs',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(12, 1664679229781704406),
        name: 'deletedAtMs',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(13, 4142305560740227200),
        name: 'type',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(14, 592499162584811244),
        name: 'metaJson',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(15, 4627179761391436070),
        name: 'membersMentionedJson',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(16, 8689335330882124842),
        name: 'editedAtMs',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(17, 3111865219569426804),
        name: 'attachmentsJson',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(18, 3645841195819333613),
        name: 'reactionsJson',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(19, 8834088747170668148),
        name: 'repliedMessageId',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(20, 8123794081491996196),
        name: 'forwardedMessageId',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(21, 7820090683604475842),
        name: 'clientMessageId',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(22, 9196135481494364333),
        name: 'nonce',
        type: 9,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(3, 159387041528573252),
    name: 'ChatRoomEntity',
    lastPropertyId: const obx_int.IdUid(16, 6581081958776782926),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 7086738367361069793),
        name: 'obxId',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 3071224221086100767),
        name: 'uid',
        type: 9,
        flags: 2080,
        indexId: const obx_int.IdUid(8, 8345661717285520248),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 846267473029534242),
        name: 'name',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 6056215781864947068),
        name: 'description',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 4442782341419146835),
        name: 'type',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 4274066795451374732),
        name: 'isPublic',
        type: 1,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 3086272398852613967),
        name: 'isCommunity',
        type: 1,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(8, 5556516381116584254),
        name: 'pictureJson',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(9, 937911346438160890),
        name: 'backgroundJson',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(10, 2726845561895391391),
        name: 'realmId',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(11, 3878804303727774085),
        name: 'accountId',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(12, 9095346400232565495),
        name: 'isPinned',
        type: 1,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(13, 2076542080892648788),
        name: 'createdAtMs',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(14, 6856514764962572216),
        name: 'updatedAtMs',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(15, 7628333420712445243),
        name: 'deletedAtMs',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(16, 6581081958776782926),
        name: 'mlsGroupId',
        type: 9,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(4, 303584633572786615),
    name: 'PostDraftEntity',
    lastPropertyId: const obx_int.IdUid(9, 719950246210594527),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 3268692317273719241),
        name: 'obxId',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 430880942128186958),
        name: 'uid',
        type: 9,
        flags: 2080,
        indexId: const obx_int.IdUid(9, 1194774540358415607),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 8052679132497973142),
        name: 'title',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 1472783692051235147),
        name: 'description',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 5137106832347835888),
        name: 'content',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 2375338123012164467),
        name: 'visibility',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 7661873262868600468),
        name: 'type',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(8, 3213170420609012348),
        name: 'lastModifiedMs',
        type: 6,
        flags: 8,
        indexId: const obx_int.IdUid(10, 1182927492407707791),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(9, 719950246210594527),
        name: 'postDataJson',
        type: 9,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(5, 2751039156396140663),
    name: 'RealmEntity',
    lastPropertyId: const obx_int.IdUid(15, 6085264042198833906),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 6017792037324914775),
        name: 'obxId',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 8584339284820487136),
        name: 'uid',
        type: 9,
        flags: 2080,
        indexId: const obx_int.IdUid(11, 7340127654314367791),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 451209088090102606),
        name: 'slug',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 2826801908937873154),
        name: 'name',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 8288565097604377961),
        name: 'description',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 2921935043980554533),
        name: 'verifiedAs',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 4430979322162823177),
        name: 'verifiedAtMs',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(8, 3170606281489189593),
        name: 'isCommunity',
        type: 1,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(9, 8352842146655765544),
        name: 'isPublic',
        type: 1,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(10, 2084973041250483985),
        name: 'pictureJson',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(11, 4053338683815969824),
        name: 'backgroundJson',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(12, 1506936787452633750),
        name: 'accountId',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(13, 6504502909121525155),
        name: 'createdAtMs',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(14, 6734044180110195333),
        name: 'updatedAtMs',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(15, 6085264042198833906),
        name: 'deletedAtMs',
        type: 6,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(6, 3095537178895020388),
    name: 'RelationshipEntity',
    lastPropertyId: const obx_int.IdUid(13, 2272909316396195841),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 33170740635239537),
        name: 'obxId',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 8655195372325808404),
        name: 'uid',
        type: 9,
        flags: 2080,
        indexId: const obx_int.IdUid(12, 5499958355336951758),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 4612520929292836377),
        name: 'accountId',
        type: 9,
        flags: 2048,
        indexId: const obx_int.IdUid(13, 7936182901814801105),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 1039120802118728946),
        name: 'relatedId',
        type: 9,
        flags: 2048,
        indexId: const obx_int.IdUid(14, 2002931559330577197),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 3470876242082734402),
        name: 'status',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 7248247478171813371),
        name: 'expiredAtMs',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 8257425303057326518),
        name: 'degradeToStatus',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(8, 3131520818702576005),
        name: 'accountJson',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(9, 8187894956261248070),
        name: 'relatedJson',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(10, 5875761167174381619),
        name: 'createdAtMs',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(11, 2137392777443781357),
        name: 'updatedAtMs',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(12, 1234810662163375352),
        name: 'deletedAtMs',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(13, 2272909316396195841),
        name: 'alias',
        type: 9,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(7, 4633006183410813102),
    name: 'StickerLookupEntity',
    lastPropertyId: const obx_int.IdUid(5, 7865606278669430545),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 4247977823785475131),
        name: 'obxId',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 7627231164332001377),
        name: 'uid',
        type: 9,
        flags: 2080,
        indexId: const obx_int.IdUid(15, 742572860041903729),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 4222578831425351276),
        name: 'stickerId',
        type: 9,
        flags: 2048,
        indexId: const obx_int.IdUid(16, 5287084145654996155),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 97195578110906178),
        name: 'stickerJson',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 7865606278669430545),
        name: 'updatedAtMs',
        type: 6,
        flags: 8,
        indexId: const obx_int.IdUid(17, 6132083275743481083),
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
];

/// Shortcut for [obx.Store.new] that passes [getObjectBoxModel] and for Flutter
/// apps by default a [directory] using `defaultStoreDirectory()` from the
/// ObjectBox Flutter library.
///
/// Note: for desktop apps it is recommended to specify a unique [directory].
///
/// See [obx.Store.new] for an explanation of all parameters.
///
/// For Flutter apps, also calls `loadObjectBoxLibraryAndroidCompat()` from
/// the ObjectBox Flutter library to fix loading the native ObjectBox library
/// on Android 6 and older.
Future<obx.Store> openStore({
  String? directory,
  int? maxDBSizeInKB,
  int? maxDataSizeInKB,
  int? fileMode,
  int? maxReaders,
  bool queriesCaseSensitiveDefault = true,
  String? macosApplicationGroup,
}) async {
  await loadObjectBoxLibraryAndroidCompat();
  return obx.Store(
    getObjectBoxModel(),
    directory: directory ?? (await defaultStoreDirectory()).path,
    maxDBSizeInKB: maxDBSizeInKB,
    maxDataSizeInKB: maxDataSizeInKB,
    fileMode: fileMode,
    maxReaders: maxReaders,
    queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
    macosApplicationGroup: macosApplicationGroup,
  );
}

/// Returns the ObjectBox model definition for this project for use with
/// [obx.Store.new].
obx_int.ModelDefinition getObjectBoxModel() {
  final model = obx_int.ModelInfo(
    // If this version is not found, it means that this file was generated
    // with an older version of the ObjectBox Dart generator.
    // Please regenerate this file with the current generator version.
    // Typically, this is done with `dart run build_runner build`.
    generatorVersion: obx_int.GeneratorVersion.v2025_12_16,
    entities: _entities,
    lastEntityId: const obx_int.IdUid(7, 4633006183410813102),
    lastIndexId: const obx_int.IdUid(17, 6132083275743481083),
    lastRelationId: const obx_int.IdUid(0, 0),
    lastSequenceId: const obx_int.IdUid(0, 0),
    retiredEntityUids: const [],
    retiredIndexUids: const [],
    retiredPropertyUids: const [5953151212427077877],
    retiredRelationUids: const [],
    modelVersion: 5,
    modelVersionParserMinimum: 5,
    version: 1,
  );

  final bindings = <Type, obx_int.EntityDefinition>{
    ChatMemberEntity: obx_int.EntityDefinition<ChatMemberEntity>(
      model: _entities[0],
      toOneRelations: (ChatMemberEntity object) => [],
      toManyRelations: (ChatMemberEntity object) => {},
      getId: (ChatMemberEntity object) => object.obxId,
      setId: (ChatMemberEntity object, int id) {
        object.obxId = id;
      },
      objectToFB: (ChatMemberEntity object, fb.Builder fbb) {
        final uidOffset = fbb.writeString(object.uid);
        final chatRoomIdOffset = fbb.writeString(object.chatRoomId);
        final accountIdOffset = fbb.writeString(object.accountId);
        final accountJsonOffset = fbb.writeString(object.accountJson);
        final nickOffset = object.nick == null
            ? null
            : fbb.writeString(object.nick!);
        fbb.startTable(14);
        fbb.addInt64(0, object.obxId);
        fbb.addOffset(1, uidOffset);
        fbb.addOffset(2, chatRoomIdOffset);
        fbb.addOffset(3, accountIdOffset);
        fbb.addOffset(4, accountJsonOffset);
        fbb.addOffset(5, nickOffset);
        fbb.addInt64(6, object.notify);
        fbb.addInt64(7, object.joinedAtMs);
        fbb.addInt64(8, object.breakUntilMs);
        fbb.addInt64(9, object.timeoutUntilMs);
        fbb.addInt64(10, object.createdAtMs);
        fbb.addInt64(11, object.updatedAtMs);
        fbb.addInt64(12, object.deletedAtMs);
        fbb.finish(fbb.endTable());
        return object.obxId;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final obxIdParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final uidParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final chatRoomIdParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 8, '');
        final accountIdParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 10, '');
        final accountJsonParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 12, '');
        final nickParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 14);
        final notifyParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          16,
          0,
        );
        final joinedAtMsParam = const fb.Int64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          18,
        );
        final breakUntilMsParam = const fb.Int64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          20,
        );
        final timeoutUntilMsParam = const fb.Int64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          22,
        );
        final createdAtMsParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          24,
          0,
        );
        final updatedAtMsParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          26,
          0,
        );
        final deletedAtMsParam = const fb.Int64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          28,
        );
        final object = ChatMemberEntity(
          obxId: obxIdParam,
          uid: uidParam,
          chatRoomId: chatRoomIdParam,
          accountId: accountIdParam,
          accountJson: accountJsonParam,
          nick: nickParam,
          notify: notifyParam,
          joinedAtMs: joinedAtMsParam,
          breakUntilMs: breakUntilMsParam,
          timeoutUntilMs: timeoutUntilMsParam,
          createdAtMs: createdAtMsParam,
          updatedAtMs: updatedAtMsParam,
          deletedAtMs: deletedAtMsParam,
        );

        return object;
      },
    ),
    ChatMessageEntity: obx_int.EntityDefinition<ChatMessageEntity>(
      model: _entities[1],
      toOneRelations: (ChatMessageEntity object) => [],
      toManyRelations: (ChatMessageEntity object) => {},
      getId: (ChatMessageEntity object) => object.obxId,
      setId: (ChatMessageEntity object, int id) {
        object.obxId = id;
      },
      objectToFB: (ChatMessageEntity object, fb.Builder fbb) {
        final uidOffset = fbb.writeString(object.uid);
        final roomIdOffset = fbb.writeString(object.roomId);
        final senderIdOffset = fbb.writeString(object.senderId);
        final contentOffset = object.content == null
            ? null
            : fbb.writeString(object.content!);
        final dataJsonOffset = fbb.writeString(object.dataJson);
        final typeOffset = fbb.writeString(object.type);
        final metaJsonOffset = fbb.writeString(object.metaJson);
        final membersMentionedJsonOffset = fbb.writeString(
          object.membersMentionedJson,
        );
        final attachmentsJsonOffset = fbb.writeString(object.attachmentsJson);
        final reactionsJsonOffset = fbb.writeString(object.reactionsJson);
        final repliedMessageIdOffset = object.repliedMessageId == null
            ? null
            : fbb.writeString(object.repliedMessageId!);
        final forwardedMessageIdOffset = object.forwardedMessageId == null
            ? null
            : fbb.writeString(object.forwardedMessageId!);
        final clientMessageIdOffset = object.clientMessageId == null
            ? null
            : fbb.writeString(object.clientMessageId!);
        final nonceOffset = object.nonce == null
            ? null
            : fbb.writeString(object.nonce!);
        fbb.startTable(23);
        fbb.addInt64(0, object.obxId);
        fbb.addOffset(1, uidOffset);
        fbb.addOffset(2, roomIdOffset);
        fbb.addOffset(3, senderIdOffset);
        fbb.addOffset(4, contentOffset);
        fbb.addOffset(6, dataJsonOffset);
        fbb.addInt64(7, object.createdAtMs);
        fbb.addInt64(8, object.status);
        fbb.addBool(9, object.isDeleted);
        fbb.addInt64(10, object.updatedAtMs);
        fbb.addInt64(11, object.deletedAtMs);
        fbb.addOffset(12, typeOffset);
        fbb.addOffset(13, metaJsonOffset);
        fbb.addOffset(14, membersMentionedJsonOffset);
        fbb.addInt64(15, object.editedAtMs);
        fbb.addOffset(16, attachmentsJsonOffset);
        fbb.addOffset(17, reactionsJsonOffset);
        fbb.addOffset(18, repliedMessageIdOffset);
        fbb.addOffset(19, forwardedMessageIdOffset);
        fbb.addOffset(20, clientMessageIdOffset);
        fbb.addOffset(21, nonceOffset);
        fbb.finish(fbb.endTable());
        return object.obxId;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final obxIdParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final uidParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final roomIdParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 8, '');
        final senderIdParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 10, '');
        final contentParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 12);
        final clientMessageIdParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 44);
        final nonceParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 46);
        final dataJsonParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 16, '');
        final createdAtMsParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          18,
          0,
        );
        final statusParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          20,
          0,
        );
        final isDeletedParam = const fb.BoolReader().vTableGet(
          buffer,
          rootOffset,
          22,
          false,
        );
        final updatedAtMsParam = const fb.Int64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          24,
        );
        final deletedAtMsParam = const fb.Int64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          26,
        );
        final typeParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 28, '');
        final metaJsonParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 30, '');
        final membersMentionedJsonParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 32, '');
        final editedAtMsParam = const fb.Int64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          34,
        );
        final attachmentsJsonParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 36, '');
        final reactionsJsonParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 38, '');
        final repliedMessageIdParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 40);
        final forwardedMessageIdParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 42);
        final object = ChatMessageEntity(
          obxId: obxIdParam,
          uid: uidParam,
          roomId: roomIdParam,
          senderId: senderIdParam,
          content: contentParam,
          clientMessageId: clientMessageIdParam,
          nonce: nonceParam,
          dataJson: dataJsonParam,
          createdAtMs: createdAtMsParam,
          status: statusParam,
          isDeleted: isDeletedParam,
          updatedAtMs: updatedAtMsParam,
          deletedAtMs: deletedAtMsParam,
          type: typeParam,
          metaJson: metaJsonParam,
          membersMentionedJson: membersMentionedJsonParam,
          editedAtMs: editedAtMsParam,
          attachmentsJson: attachmentsJsonParam,
          reactionsJson: reactionsJsonParam,
          repliedMessageId: repliedMessageIdParam,
          forwardedMessageId: forwardedMessageIdParam,
        );

        return object;
      },
    ),
    ChatRoomEntity: obx_int.EntityDefinition<ChatRoomEntity>(
      model: _entities[2],
      toOneRelations: (ChatRoomEntity object) => [],
      toManyRelations: (ChatRoomEntity object) => {},
      getId: (ChatRoomEntity object) => object.obxId,
      setId: (ChatRoomEntity object, int id) {
        object.obxId = id;
      },
      objectToFB: (ChatRoomEntity object, fb.Builder fbb) {
        final uidOffset = fbb.writeString(object.uid);
        final nameOffset = object.name == null
            ? null
            : fbb.writeString(object.name!);
        final descriptionOffset = object.description == null
            ? null
            : fbb.writeString(object.description!);
        final pictureJsonOffset = object.pictureJson == null
            ? null
            : fbb.writeString(object.pictureJson!);
        final backgroundJsonOffset = object.backgroundJson == null
            ? null
            : fbb.writeString(object.backgroundJson!);
        final realmIdOffset = object.realmId == null
            ? null
            : fbb.writeString(object.realmId!);
        final accountIdOffset = object.accountId == null
            ? null
            : fbb.writeString(object.accountId!);
        final mlsGroupIdOffset = object.mlsGroupId == null
            ? null
            : fbb.writeString(object.mlsGroupId!);
        fbb.startTable(17);
        fbb.addInt64(0, object.obxId);
        fbb.addOffset(1, uidOffset);
        fbb.addOffset(2, nameOffset);
        fbb.addOffset(3, descriptionOffset);
        fbb.addInt64(4, object.type);
        fbb.addBool(5, object.isPublic);
        fbb.addBool(6, object.isCommunity);
        fbb.addOffset(7, pictureJsonOffset);
        fbb.addOffset(8, backgroundJsonOffset);
        fbb.addOffset(9, realmIdOffset);
        fbb.addOffset(10, accountIdOffset);
        fbb.addBool(11, object.isPinned);
        fbb.addInt64(12, object.createdAtMs);
        fbb.addInt64(13, object.updatedAtMs);
        fbb.addInt64(14, object.deletedAtMs);
        fbb.addOffset(15, mlsGroupIdOffset);
        fbb.finish(fbb.endTable());
        return object.obxId;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final obxIdParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final uidParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final nameParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 8);
        final descriptionParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 10);
        final typeParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          12,
          0,
        );
        final isPublicParam = const fb.BoolReader().vTableGet(
          buffer,
          rootOffset,
          14,
          false,
        );
        final isCommunityParam = const fb.BoolReader().vTableGet(
          buffer,
          rootOffset,
          16,
          false,
        );
        final pictureJsonParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 18);
        final backgroundJsonParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 20);
        final realmIdParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 22);
        final accountIdParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 24);
        final mlsGroupIdParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 34);
        final isPinnedParam = const fb.BoolReader().vTableGet(
          buffer,
          rootOffset,
          26,
          false,
        );
        final createdAtMsParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          28,
          0,
        );
        final updatedAtMsParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          30,
          0,
        );
        final deletedAtMsParam = const fb.Int64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          32,
        );
        final object = ChatRoomEntity(
          obxId: obxIdParam,
          uid: uidParam,
          name: nameParam,
          description: descriptionParam,
          type: typeParam,
          isPublic: isPublicParam,
          isCommunity: isCommunityParam,
          pictureJson: pictureJsonParam,
          backgroundJson: backgroundJsonParam,
          realmId: realmIdParam,
          accountId: accountIdParam,
          mlsGroupId: mlsGroupIdParam,
          isPinned: isPinnedParam,
          createdAtMs: createdAtMsParam,
          updatedAtMs: updatedAtMsParam,
          deletedAtMs: deletedAtMsParam,
        );

        return object;
      },
    ),
    PostDraftEntity: obx_int.EntityDefinition<PostDraftEntity>(
      model: _entities[3],
      toOneRelations: (PostDraftEntity object) => [],
      toManyRelations: (PostDraftEntity object) => {},
      getId: (PostDraftEntity object) => object.obxId,
      setId: (PostDraftEntity object, int id) {
        object.obxId = id;
      },
      objectToFB: (PostDraftEntity object, fb.Builder fbb) {
        final uidOffset = fbb.writeString(object.uid);
        final titleOffset = object.title == null
            ? null
            : fbb.writeString(object.title!);
        final descriptionOffset = object.description == null
            ? null
            : fbb.writeString(object.description!);
        final contentOffset = object.content == null
            ? null
            : fbb.writeString(object.content!);
        final postDataJsonOffset = fbb.writeString(object.postDataJson);
        fbb.startTable(10);
        fbb.addInt64(0, object.obxId);
        fbb.addOffset(1, uidOffset);
        fbb.addOffset(2, titleOffset);
        fbb.addOffset(3, descriptionOffset);
        fbb.addOffset(4, contentOffset);
        fbb.addInt64(5, object.visibility);
        fbb.addInt64(6, object.type);
        fbb.addInt64(7, object.lastModifiedMs);
        fbb.addOffset(8, postDataJsonOffset);
        fbb.finish(fbb.endTable());
        return object.obxId;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final obxIdParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final uidParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final titleParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 8);
        final descriptionParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 10);
        final contentParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 12);
        final visibilityParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          14,
          0,
        );
        final typeParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          16,
          0,
        );
        final lastModifiedMsParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          18,
          0,
        );
        final postDataJsonParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 20, '');
        final object = PostDraftEntity(
          obxId: obxIdParam,
          uid: uidParam,
          title: titleParam,
          description: descriptionParam,
          content: contentParam,
          visibility: visibilityParam,
          type: typeParam,
          lastModifiedMs: lastModifiedMsParam,
          postDataJson: postDataJsonParam,
        );

        return object;
      },
    ),
    RealmEntity: obx_int.EntityDefinition<RealmEntity>(
      model: _entities[4],
      toOneRelations: (RealmEntity object) => [],
      toManyRelations: (RealmEntity object) => {},
      getId: (RealmEntity object) => object.obxId,
      setId: (RealmEntity object, int id) {
        object.obxId = id;
      },
      objectToFB: (RealmEntity object, fb.Builder fbb) {
        final uidOffset = fbb.writeString(object.uid);
        final slugOffset = fbb.writeString(object.slug);
        final nameOffset = object.name == null
            ? null
            : fbb.writeString(object.name!);
        final descriptionOffset = object.description == null
            ? null
            : fbb.writeString(object.description!);
        final verifiedAsOffset = object.verifiedAs == null
            ? null
            : fbb.writeString(object.verifiedAs!);
        final pictureJsonOffset = object.pictureJson == null
            ? null
            : fbb.writeString(object.pictureJson!);
        final backgroundJsonOffset = object.backgroundJson == null
            ? null
            : fbb.writeString(object.backgroundJson!);
        final accountIdOffset = object.accountId == null
            ? null
            : fbb.writeString(object.accountId!);
        fbb.startTable(16);
        fbb.addInt64(0, object.obxId);
        fbb.addOffset(1, uidOffset);
        fbb.addOffset(2, slugOffset);
        fbb.addOffset(3, nameOffset);
        fbb.addOffset(4, descriptionOffset);
        fbb.addOffset(5, verifiedAsOffset);
        fbb.addInt64(6, object.verifiedAtMs);
        fbb.addBool(7, object.isCommunity);
        fbb.addBool(8, object.isPublic);
        fbb.addOffset(9, pictureJsonOffset);
        fbb.addOffset(10, backgroundJsonOffset);
        fbb.addOffset(11, accountIdOffset);
        fbb.addInt64(12, object.createdAtMs);
        fbb.addInt64(13, object.updatedAtMs);
        fbb.addInt64(14, object.deletedAtMs);
        fbb.finish(fbb.endTable());
        return object.obxId;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final obxIdParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final uidParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final slugParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 8, '');
        final nameParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 10);
        final descriptionParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 12);
        final verifiedAsParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 14);
        final verifiedAtMsParam = const fb.Int64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          16,
        );
        final isCommunityParam = const fb.BoolReader().vTableGet(
          buffer,
          rootOffset,
          18,
          false,
        );
        final isPublicParam = const fb.BoolReader().vTableGet(
          buffer,
          rootOffset,
          20,
          false,
        );
        final pictureJsonParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 22);
        final backgroundJsonParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 24);
        final accountIdParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 26);
        final createdAtMsParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          28,
          0,
        );
        final updatedAtMsParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          30,
          0,
        );
        final deletedAtMsParam = const fb.Int64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          32,
        );
        final object = RealmEntity(
          obxId: obxIdParam,
          uid: uidParam,
          slug: slugParam,
          name: nameParam,
          description: descriptionParam,
          verifiedAs: verifiedAsParam,
          verifiedAtMs: verifiedAtMsParam,
          isCommunity: isCommunityParam,
          isPublic: isPublicParam,
          pictureJson: pictureJsonParam,
          backgroundJson: backgroundJsonParam,
          accountId: accountIdParam,
          createdAtMs: createdAtMsParam,
          updatedAtMs: updatedAtMsParam,
          deletedAtMs: deletedAtMsParam,
        );

        return object;
      },
    ),
    RelationshipEntity: obx_int.EntityDefinition<RelationshipEntity>(
      model: _entities[5],
      toOneRelations: (RelationshipEntity object) => [],
      toManyRelations: (RelationshipEntity object) => {},
      getId: (RelationshipEntity object) => object.obxId,
      setId: (RelationshipEntity object, int id) {
        object.obxId = id;
      },
      objectToFB: (RelationshipEntity object, fb.Builder fbb) {
        final uidOffset = fbb.writeString(object.uid);
        final accountIdOffset = fbb.writeString(object.accountId);
        final relatedIdOffset = fbb.writeString(object.relatedId);
        final accountJsonOffset = object.accountJson == null
            ? null
            : fbb.writeString(object.accountJson!);
        final relatedJsonOffset = object.relatedJson == null
            ? null
            : fbb.writeString(object.relatedJson!);
        final aliasOffset = object.alias == null
            ? null
            : fbb.writeString(object.alias!);
        fbb.startTable(14);
        fbb.addInt64(0, object.obxId);
        fbb.addOffset(1, uidOffset);
        fbb.addOffset(2, accountIdOffset);
        fbb.addOffset(3, relatedIdOffset);
        fbb.addInt64(4, object.status);
        fbb.addInt64(5, object.expiredAtMs);
        fbb.addInt64(6, object.degradeToStatus);
        fbb.addOffset(7, accountJsonOffset);
        fbb.addOffset(8, relatedJsonOffset);
        fbb.addInt64(9, object.createdAtMs);
        fbb.addInt64(10, object.updatedAtMs);
        fbb.addInt64(11, object.deletedAtMs);
        fbb.addOffset(12, aliasOffset);
        fbb.finish(fbb.endTable());
        return object.obxId;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final obxIdParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final uidParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final accountIdParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 8, '');
        final relatedIdParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 10, '');
        final statusParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          12,
          0,
        );
        final expiredAtMsParam = const fb.Int64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          14,
        );
        final degradeToStatusParam = const fb.Int64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          16,
        );
        final aliasParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 28);
        final accountJsonParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 18);
        final relatedJsonParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 20);
        final createdAtMsParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          22,
          0,
        );
        final updatedAtMsParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          24,
          0,
        );
        final deletedAtMsParam = const fb.Int64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          26,
        );
        final object = RelationshipEntity(
          obxId: obxIdParam,
          uid: uidParam,
          accountId: accountIdParam,
          relatedId: relatedIdParam,
          status: statusParam,
          expiredAtMs: expiredAtMsParam,
          degradeToStatus: degradeToStatusParam,
          alias: aliasParam,
          accountJson: accountJsonParam,
          relatedJson: relatedJsonParam,
          createdAtMs: createdAtMsParam,
          updatedAtMs: updatedAtMsParam,
          deletedAtMs: deletedAtMsParam,
        );

        return object;
      },
    ),
    StickerLookupEntity: obx_int.EntityDefinition<StickerLookupEntity>(
      model: _entities[6],
      toOneRelations: (StickerLookupEntity object) => [],
      toManyRelations: (StickerLookupEntity object) => {},
      getId: (StickerLookupEntity object) => object.obxId,
      setId: (StickerLookupEntity object, int id) {
        object.obxId = id;
      },
      objectToFB: (StickerLookupEntity object, fb.Builder fbb) {
        final uidOffset = fbb.writeString(object.uid);
        final stickerIdOffset = fbb.writeString(object.stickerId);
        final stickerJsonOffset = fbb.writeString(object.stickerJson);
        fbb.startTable(6);
        fbb.addInt64(0, object.obxId);
        fbb.addOffset(1, uidOffset);
        fbb.addOffset(2, stickerIdOffset);
        fbb.addOffset(3, stickerJsonOffset);
        fbb.addInt64(4, object.updatedAtMs);
        fbb.finish(fbb.endTable());
        return object.obxId;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final obxIdParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final uidParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final stickerIdParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 8, '');
        final stickerJsonParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 10, '');
        final updatedAtMsParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          12,
          0,
        );
        final object = StickerLookupEntity(
          obxId: obxIdParam,
          uid: uidParam,
          stickerId: stickerIdParam,
          stickerJson: stickerJsonParam,
          updatedAtMs: updatedAtMsParam,
        );

        return object;
      },
    ),
  };

  return obx_int.ModelDefinition(model, bindings);
}

/// [ChatMemberEntity] entity fields to define ObjectBox queries.
class ChatMemberEntity_ {
  /// See [ChatMemberEntity.obxId].
  static final obxId = obx.QueryIntegerProperty<ChatMemberEntity>(
    _entities[0].properties[0],
  );

  /// See [ChatMemberEntity.uid].
  static final uid = obx.QueryStringProperty<ChatMemberEntity>(
    _entities[0].properties[1],
  );

  /// See [ChatMemberEntity.chatRoomId].
  static final chatRoomId = obx.QueryStringProperty<ChatMemberEntity>(
    _entities[0].properties[2],
  );

  /// See [ChatMemberEntity.accountId].
  static final accountId = obx.QueryStringProperty<ChatMemberEntity>(
    _entities[0].properties[3],
  );

  /// See [ChatMemberEntity.accountJson].
  static final accountJson = obx.QueryStringProperty<ChatMemberEntity>(
    _entities[0].properties[4],
  );

  /// See [ChatMemberEntity.nick].
  static final nick = obx.QueryStringProperty<ChatMemberEntity>(
    _entities[0].properties[5],
  );

  /// See [ChatMemberEntity.notify].
  static final notify = obx.QueryIntegerProperty<ChatMemberEntity>(
    _entities[0].properties[6],
  );

  /// See [ChatMemberEntity.joinedAtMs].
  static final joinedAtMs = obx.QueryIntegerProperty<ChatMemberEntity>(
    _entities[0].properties[7],
  );

  /// See [ChatMemberEntity.breakUntilMs].
  static final breakUntilMs = obx.QueryIntegerProperty<ChatMemberEntity>(
    _entities[0].properties[8],
  );

  /// See [ChatMemberEntity.timeoutUntilMs].
  static final timeoutUntilMs = obx.QueryIntegerProperty<ChatMemberEntity>(
    _entities[0].properties[9],
  );

  /// See [ChatMemberEntity.createdAtMs].
  static final createdAtMs = obx.QueryIntegerProperty<ChatMemberEntity>(
    _entities[0].properties[10],
  );

  /// See [ChatMemberEntity.updatedAtMs].
  static final updatedAtMs = obx.QueryIntegerProperty<ChatMemberEntity>(
    _entities[0].properties[11],
  );

  /// See [ChatMemberEntity.deletedAtMs].
  static final deletedAtMs = obx.QueryIntegerProperty<ChatMemberEntity>(
    _entities[0].properties[12],
  );
}

/// [ChatMessageEntity] entity fields to define ObjectBox queries.
class ChatMessageEntity_ {
  /// See [ChatMessageEntity.obxId].
  static final obxId = obx.QueryIntegerProperty<ChatMessageEntity>(
    _entities[1].properties[0],
  );

  /// See [ChatMessageEntity.uid].
  static final uid = obx.QueryStringProperty<ChatMessageEntity>(
    _entities[1].properties[1],
  );

  /// See [ChatMessageEntity.roomId].
  static final roomId = obx.QueryStringProperty<ChatMessageEntity>(
    _entities[1].properties[2],
  );

  /// See [ChatMessageEntity.senderId].
  static final senderId = obx.QueryStringProperty<ChatMessageEntity>(
    _entities[1].properties[3],
  );

  /// See [ChatMessageEntity.content].
  static final content = obx.QueryStringProperty<ChatMessageEntity>(
    _entities[1].properties[4],
  );

  /// See [ChatMessageEntity.dataJson].
  static final dataJson = obx.QueryStringProperty<ChatMessageEntity>(
    _entities[1].properties[5],
  );

  /// See [ChatMessageEntity.createdAtMs].
  static final createdAtMs = obx.QueryIntegerProperty<ChatMessageEntity>(
    _entities[1].properties[6],
  );

  /// See [ChatMessageEntity.status].
  static final status = obx.QueryIntegerProperty<ChatMessageEntity>(
    _entities[1].properties[7],
  );

  /// See [ChatMessageEntity.isDeleted].
  static final isDeleted = obx.QueryBooleanProperty<ChatMessageEntity>(
    _entities[1].properties[8],
  );

  /// See [ChatMessageEntity.updatedAtMs].
  static final updatedAtMs = obx.QueryIntegerProperty<ChatMessageEntity>(
    _entities[1].properties[9],
  );

  /// See [ChatMessageEntity.deletedAtMs].
  static final deletedAtMs = obx.QueryIntegerProperty<ChatMessageEntity>(
    _entities[1].properties[10],
  );

  /// See [ChatMessageEntity.type].
  static final type = obx.QueryStringProperty<ChatMessageEntity>(
    _entities[1].properties[11],
  );

  /// See [ChatMessageEntity.metaJson].
  static final metaJson = obx.QueryStringProperty<ChatMessageEntity>(
    _entities[1].properties[12],
  );

  /// See [ChatMessageEntity.membersMentionedJson].
  static final membersMentionedJson =
      obx.QueryStringProperty<ChatMessageEntity>(_entities[1].properties[13]);

  /// See [ChatMessageEntity.editedAtMs].
  static final editedAtMs = obx.QueryIntegerProperty<ChatMessageEntity>(
    _entities[1].properties[14],
  );

  /// See [ChatMessageEntity.attachmentsJson].
  static final attachmentsJson = obx.QueryStringProperty<ChatMessageEntity>(
    _entities[1].properties[15],
  );

  /// See [ChatMessageEntity.reactionsJson].
  static final reactionsJson = obx.QueryStringProperty<ChatMessageEntity>(
    _entities[1].properties[16],
  );

  /// See [ChatMessageEntity.repliedMessageId].
  static final repliedMessageId = obx.QueryStringProperty<ChatMessageEntity>(
    _entities[1].properties[17],
  );

  /// See [ChatMessageEntity.forwardedMessageId].
  static final forwardedMessageId = obx.QueryStringProperty<ChatMessageEntity>(
    _entities[1].properties[18],
  );

  /// See [ChatMessageEntity.clientMessageId].
  static final clientMessageId = obx.QueryStringProperty<ChatMessageEntity>(
    _entities[1].properties[19],
  );

  /// See [ChatMessageEntity.nonce].
  static final nonce = obx.QueryStringProperty<ChatMessageEntity>(
    _entities[1].properties[20],
  );
}

/// [ChatRoomEntity] entity fields to define ObjectBox queries.
class ChatRoomEntity_ {
  /// See [ChatRoomEntity.obxId].
  static final obxId = obx.QueryIntegerProperty<ChatRoomEntity>(
    _entities[2].properties[0],
  );

  /// See [ChatRoomEntity.uid].
  static final uid = obx.QueryStringProperty<ChatRoomEntity>(
    _entities[2].properties[1],
  );

  /// See [ChatRoomEntity.name].
  static final name = obx.QueryStringProperty<ChatRoomEntity>(
    _entities[2].properties[2],
  );

  /// See [ChatRoomEntity.description].
  static final description = obx.QueryStringProperty<ChatRoomEntity>(
    _entities[2].properties[3],
  );

  /// See [ChatRoomEntity.type].
  static final type = obx.QueryIntegerProperty<ChatRoomEntity>(
    _entities[2].properties[4],
  );

  /// See [ChatRoomEntity.isPublic].
  static final isPublic = obx.QueryBooleanProperty<ChatRoomEntity>(
    _entities[2].properties[5],
  );

  /// See [ChatRoomEntity.isCommunity].
  static final isCommunity = obx.QueryBooleanProperty<ChatRoomEntity>(
    _entities[2].properties[6],
  );

  /// See [ChatRoomEntity.pictureJson].
  static final pictureJson = obx.QueryStringProperty<ChatRoomEntity>(
    _entities[2].properties[7],
  );

  /// See [ChatRoomEntity.backgroundJson].
  static final backgroundJson = obx.QueryStringProperty<ChatRoomEntity>(
    _entities[2].properties[8],
  );

  /// See [ChatRoomEntity.realmId].
  static final realmId = obx.QueryStringProperty<ChatRoomEntity>(
    _entities[2].properties[9],
  );

  /// See [ChatRoomEntity.accountId].
  static final accountId = obx.QueryStringProperty<ChatRoomEntity>(
    _entities[2].properties[10],
  );

  /// See [ChatRoomEntity.isPinned].
  static final isPinned = obx.QueryBooleanProperty<ChatRoomEntity>(
    _entities[2].properties[11],
  );

  /// See [ChatRoomEntity.createdAtMs].
  static final createdAtMs = obx.QueryIntegerProperty<ChatRoomEntity>(
    _entities[2].properties[12],
  );

  /// See [ChatRoomEntity.updatedAtMs].
  static final updatedAtMs = obx.QueryIntegerProperty<ChatRoomEntity>(
    _entities[2].properties[13],
  );

  /// See [ChatRoomEntity.deletedAtMs].
  static final deletedAtMs = obx.QueryIntegerProperty<ChatRoomEntity>(
    _entities[2].properties[14],
  );

  /// See [ChatRoomEntity.mlsGroupId].
  static final mlsGroupId = obx.QueryStringProperty<ChatRoomEntity>(
    _entities[2].properties[15],
  );
}

/// [PostDraftEntity] entity fields to define ObjectBox queries.
class PostDraftEntity_ {
  /// See [PostDraftEntity.obxId].
  static final obxId = obx.QueryIntegerProperty<PostDraftEntity>(
    _entities[3].properties[0],
  );

  /// See [PostDraftEntity.uid].
  static final uid = obx.QueryStringProperty<PostDraftEntity>(
    _entities[3].properties[1],
  );

  /// See [PostDraftEntity.title].
  static final title = obx.QueryStringProperty<PostDraftEntity>(
    _entities[3].properties[2],
  );

  /// See [PostDraftEntity.description].
  static final description = obx.QueryStringProperty<PostDraftEntity>(
    _entities[3].properties[3],
  );

  /// See [PostDraftEntity.content].
  static final content = obx.QueryStringProperty<PostDraftEntity>(
    _entities[3].properties[4],
  );

  /// See [PostDraftEntity.visibility].
  static final visibility = obx.QueryIntegerProperty<PostDraftEntity>(
    _entities[3].properties[5],
  );

  /// See [PostDraftEntity.type].
  static final type = obx.QueryIntegerProperty<PostDraftEntity>(
    _entities[3].properties[6],
  );

  /// See [PostDraftEntity.lastModifiedMs].
  static final lastModifiedMs = obx.QueryIntegerProperty<PostDraftEntity>(
    _entities[3].properties[7],
  );

  /// See [PostDraftEntity.postDataJson].
  static final postDataJson = obx.QueryStringProperty<PostDraftEntity>(
    _entities[3].properties[8],
  );
}

/// [RealmEntity] entity fields to define ObjectBox queries.
class RealmEntity_ {
  /// See [RealmEntity.obxId].
  static final obxId = obx.QueryIntegerProperty<RealmEntity>(
    _entities[4].properties[0],
  );

  /// See [RealmEntity.uid].
  static final uid = obx.QueryStringProperty<RealmEntity>(
    _entities[4].properties[1],
  );

  /// See [RealmEntity.slug].
  static final slug = obx.QueryStringProperty<RealmEntity>(
    _entities[4].properties[2],
  );

  /// See [RealmEntity.name].
  static final name = obx.QueryStringProperty<RealmEntity>(
    _entities[4].properties[3],
  );

  /// See [RealmEntity.description].
  static final description = obx.QueryStringProperty<RealmEntity>(
    _entities[4].properties[4],
  );

  /// See [RealmEntity.verifiedAs].
  static final verifiedAs = obx.QueryStringProperty<RealmEntity>(
    _entities[4].properties[5],
  );

  /// See [RealmEntity.verifiedAtMs].
  static final verifiedAtMs = obx.QueryIntegerProperty<RealmEntity>(
    _entities[4].properties[6],
  );

  /// See [RealmEntity.isCommunity].
  static final isCommunity = obx.QueryBooleanProperty<RealmEntity>(
    _entities[4].properties[7],
  );

  /// See [RealmEntity.isPublic].
  static final isPublic = obx.QueryBooleanProperty<RealmEntity>(
    _entities[4].properties[8],
  );

  /// See [RealmEntity.pictureJson].
  static final pictureJson = obx.QueryStringProperty<RealmEntity>(
    _entities[4].properties[9],
  );

  /// See [RealmEntity.backgroundJson].
  static final backgroundJson = obx.QueryStringProperty<RealmEntity>(
    _entities[4].properties[10],
  );

  /// See [RealmEntity.accountId].
  static final accountId = obx.QueryStringProperty<RealmEntity>(
    _entities[4].properties[11],
  );

  /// See [RealmEntity.createdAtMs].
  static final createdAtMs = obx.QueryIntegerProperty<RealmEntity>(
    _entities[4].properties[12],
  );

  /// See [RealmEntity.updatedAtMs].
  static final updatedAtMs = obx.QueryIntegerProperty<RealmEntity>(
    _entities[4].properties[13],
  );

  /// See [RealmEntity.deletedAtMs].
  static final deletedAtMs = obx.QueryIntegerProperty<RealmEntity>(
    _entities[4].properties[14],
  );
}

/// [RelationshipEntity] entity fields to define ObjectBox queries.
class RelationshipEntity_ {
  /// See [RelationshipEntity.obxId].
  static final obxId = obx.QueryIntegerProperty<RelationshipEntity>(
    _entities[5].properties[0],
  );

  /// See [RelationshipEntity.uid].
  static final uid = obx.QueryStringProperty<RelationshipEntity>(
    _entities[5].properties[1],
  );

  /// See [RelationshipEntity.accountId].
  static final accountId = obx.QueryStringProperty<RelationshipEntity>(
    _entities[5].properties[2],
  );

  /// See [RelationshipEntity.relatedId].
  static final relatedId = obx.QueryStringProperty<RelationshipEntity>(
    _entities[5].properties[3],
  );

  /// See [RelationshipEntity.status].
  static final status = obx.QueryIntegerProperty<RelationshipEntity>(
    _entities[5].properties[4],
  );

  /// See [RelationshipEntity.expiredAtMs].
  static final expiredAtMs = obx.QueryIntegerProperty<RelationshipEntity>(
    _entities[5].properties[5],
  );

  /// See [RelationshipEntity.degradeToStatus].
  static final degradeToStatus = obx.QueryIntegerProperty<RelationshipEntity>(
    _entities[5].properties[6],
  );

  /// See [RelationshipEntity.accountJson].
  static final accountJson = obx.QueryStringProperty<RelationshipEntity>(
    _entities[5].properties[7],
  );

  /// See [RelationshipEntity.relatedJson].
  static final relatedJson = obx.QueryStringProperty<RelationshipEntity>(
    _entities[5].properties[8],
  );

  /// See [RelationshipEntity.createdAtMs].
  static final createdAtMs = obx.QueryIntegerProperty<RelationshipEntity>(
    _entities[5].properties[9],
  );

  /// See [RelationshipEntity.updatedAtMs].
  static final updatedAtMs = obx.QueryIntegerProperty<RelationshipEntity>(
    _entities[5].properties[10],
  );

  /// See [RelationshipEntity.deletedAtMs].
  static final deletedAtMs = obx.QueryIntegerProperty<RelationshipEntity>(
    _entities[5].properties[11],
  );

  /// See [RelationshipEntity.alias].
  static final alias = obx.QueryStringProperty<RelationshipEntity>(
    _entities[5].properties[12],
  );
}

/// [StickerLookupEntity] entity fields to define ObjectBox queries.
class StickerLookupEntity_ {
  /// See [StickerLookupEntity.obxId].
  static final obxId = obx.QueryIntegerProperty<StickerLookupEntity>(
    _entities[6].properties[0],
  );

  /// See [StickerLookupEntity.uid].
  static final uid = obx.QueryStringProperty<StickerLookupEntity>(
    _entities[6].properties[1],
  );

  /// See [StickerLookupEntity.stickerId].
  static final stickerId = obx.QueryStringProperty<StickerLookupEntity>(
    _entities[6].properties[2],
  );

  /// See [StickerLookupEntity.stickerJson].
  static final stickerJson = obx.QueryStringProperty<StickerLookupEntity>(
    _entities[6].properties[3],
  );

  /// See [StickerLookupEntity.updatedAtMs].
  static final updatedAtMs = obx.QueryIntegerProperty<StickerLookupEntity>(
    _entities[6].properties[4],
  );
}
