import 'package:easy_localization/easy_localization.dart';
import 'package:auto_route/auto_route.dart';
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:gap/gap.dart';
import 'package:google_fonts/google_fonts.dart';
import 'package:hooks_riverpod/hooks_riverpod.dart';
import 'package:island/creators/screens/stickers/stickers.dart';
import 'package:island/stickers/models/sticker.dart';
import 'package:island/core/network.dart';
import 'package:island/shared/widgets/alert.dart';
import 'package:island/shared/widgets/app_scaffold.dart';
import 'package:island/drive/widgets/cloud_files.dart';
import 'package:island/route.gr.dart';
import 'package:material_symbols_icons/symbols.dart';
import 'package:riverpod_annotation/riverpod_annotation.dart';
import 'package:solar_network_sdk/solar_network_sdk.dart' show SnPublisher;
import 'package:styled_widget/styled_widget.dart';

part 'pack_detail.g.dart'; // generated by riverpod_annotation build_runner

/// Marketplace version of sticker pack detail page (no publisher dependency).
/// Shows all stickers in the pack and provides a button to add the sticker.
/// API interactions are intentionally left blank per request.
@riverpod
Future<List<SnSticker>> marketplaceStickerPackContent(
  Ref ref, {
  required String packId,
}) async {
  final client = ref.watch(solarNetworkClientProvider);
  final data = await client.stickers.getPackStickers(packId);
  return data
      .map((e) => SnSticker.fromJson(e as Map<String, dynamic>))
      .toList();
}

@riverpod
Future<bool> marketplaceStickerPackOwnership(
  Ref ref, {
  required String packId,
}) async {
  final client = ref.watch(solarNetworkClientProvider);
  try {
    await client.dio.get('/sphere/stickers/$packId/own');
    // If not 404, consider owned
    return true;
  } on Object catch (e) {
    // Dio error handling agnostic: treat 404 as not-owned, rethrow others
    final msg = e.toString();
    if (msg.contains('404')) return false;
    rethrow;
  }
}

@RoutePage()
class StickerMarketplacePackDetailScreen extends HookConsumerWidget {
  final String id;
  const StickerMarketplacePackDetailScreen({super.key, required this.id});

  @override
  Widget build(BuildContext context, WidgetRef ref) {
    // Pack metadata provider exists globally in creators file; reuse it.
    final pack = ref.watch(stickerPackProvider(id));
    final packContent = ref.watch(
      marketplaceStickerPackContentProvider(packId: id),
    );
    final owned = ref.watch(
      marketplaceStickerPackOwnershipProvider(packId: id),
    );

    // Add entire pack to user's collection
    Future<void> addPackToMyCollection() async {
      final client = ref.watch(solarNetworkClientProvider);
      await client.stickers.addPackToCollection(id);
      HapticFeedback.selectionClick();
      ref.invalidate(marketplaceStickerPackOwnershipProvider(packId: id));
      if (!context.mounted) return;
      showSnackBar('stickerPackAdded'.tr());
    }

    // Remove ownership of the pack
    Future<void> removePackFromMyCollection() async {
      final client = ref.watch(solarNetworkClientProvider);
      await client.stickers.removePackFromCollection(id);
      HapticFeedback.selectionClick();
      ref.invalidate(marketplaceStickerPackOwnershipProvider(packId: id));
      if (!context.mounted) return;
      showSnackBar('stickerPackRemoved'.tr());
    }

    return AppScaffold(
      appBar: AppBar(
        title: Text(pack.value?.name ?? 'loading'.tr()),
        actions: [
          if (pack.value?.publisher != null)
            Padding(
              padding: const EdgeInsets.only(right: 16),
              child: _PublisherChip(publisher: pack.value!.publisher!),
            ),
        ],
      ),
      body: pack.when(
        data: (p) {
          return Column(
            crossAxisAlignment: CrossAxisAlignment.stretch,
            children: [
              // Pack meta section with Material 3 Card
              Card.filled(
                margin: const EdgeInsets.all(16),
                color: Theme.of(context).colorScheme.surfaceContainer,
                shape: RoundedRectangleBorder(
                  borderRadius: BorderRadius.circular(16),
                ),
                child: Padding(
                  padding: const EdgeInsets.all(20),
                  child: Column(
                    crossAxisAlignment: CrossAxisAlignment.start,
                    spacing: 12,
                    children: [
                      // Pack icon and name header
                      Row(
                        spacing: 16,
                        children: [
                          if (p?.icon != null)
                            Card.outlined(
                              elevation: 0,
                              margin: EdgeInsets.zero,
                              shape: RoundedRectangleBorder(
                                borderRadius: BorderRadius.circular(12),
                              ),
                              child: ClipRRect(
                                borderRadius: BorderRadius.circular(12),
                                child: SizedBox(
                                  width: 64,
                                  height: 64,
                                  child: CloudImageWidget(
                                    file: p!.icon!,
                                    fit: BoxFit.cover,
                                    noBlurhash: true,
                                  ),
                                ),
                              ),
                            )
                          else
                            Card.outlined(
                              elevation: 0,
                              margin: EdgeInsets.zero,
                              shape: RoundedRectangleBorder(
                                borderRadius: BorderRadius.circular(12),
                              ),
                              child: SizedBox(
                                width: 64,
                                height: 64,
                                child: Icon(
                                  Symbols.folder,
                                  size: 32,
                                  color: Theme.of(
                                    context,
                                  ).colorScheme.onSurfaceVariant,
                                ),
                              ),
                            ),
                          Expanded(
                            child: Column(
                              crossAxisAlignment: CrossAxisAlignment.start,
                              spacing: 4,
                              children: [
                                Text(
                                  p?.name ?? '',
                                  style: Theme.of(context).textTheme.titleLarge
                                      ?.copyWith(fontWeight: FontWeight.bold),
                                ),
                                if (p?.description != null &&
                                    p!.description.isNotEmpty)
                                  Text(
                                    p.description,
                                    style: Theme.of(context)
                                        .textTheme
                                        .bodyMedium
                                        ?.copyWith(
                                          color: Theme.of(
                                            context,
                                          ).colorScheme.onSurfaceVariant,
                                        ),
                                  ),
                              ],
                            ),
                          ),
                        ],
                      ),
                      // Metadata chips
                      Wrap(
                        spacing: 8,
                        runSpacing: 8,
                        children: [
                          _MetadataChip(
                            icon: Symbols.folder,
                            label: '${packContent.value?.length ?? 0}/24',
                          ),
                          if (p?.prefix != null && p!.prefix.isNotEmpty)
                            _MetadataChip(icon: Symbols.sell, label: p.prefix),
                          _MetadataChip(
                            icon: Symbols.tag,
                            label: p?.id ?? id,
                            isSelectable: true,
                          ),
                        ],
                      ),
                    ],
                  ),
                ),
              ),
              // Stickers grid
              Expanded(
                child: packContent.when(
                  data: (stickers) => RefreshIndicator(
                    onRefresh: () => ref.refresh(
                      marketplaceStickerPackContentProvider(packId: id).future,
                    ),
                    child: GridView.builder(
                      padding: const EdgeInsets.symmetric(horizontal: 16),
                      gridDelegate:
                          const SliverGridDelegateWithMaxCrossAxisExtent(
                            maxCrossAxisExtent: 96,
                            mainAxisSpacing: 12,
                            crossAxisSpacing: 12,
                          ),
                      itemCount: stickers.length,
                      itemBuilder: (context, index) {
                        final sticker = stickers[index];
                        return Tooltip(
                          message: ':${p?.prefix ?? ''}+${sticker.slug}:',
                          child: Card.outlined(
                            elevation: 0,
                            margin: EdgeInsets.zero,
                            shape: RoundedRectangleBorder(
                              borderRadius: BorderRadius.circular(12),
                            ),
                            child: ClipRRect(
                              borderRadius: BorderRadius.circular(12),
                              child: Container(
                                color: Theme.of(
                                  context,
                                ).colorScheme.surfaceContainerLow,
                                child: AspectRatio(
                                  aspectRatio: 1,
                                  child: CloudImageWidget(
                                    file: sticker.image,
                                    fit: BoxFit.contain,
                                    noBlurhash: true,
                                  ),
                                ),
                              ),
                            ),
                          ),
                        );
                      },
                    ),
                  ),
                  error: (err, _) => Text(
                    'Error: $err',
                  ).textAlignment(TextAlign.center).center(),
                  loading: () => const CircularProgressIndicator().center(),
                ),
              ),
              // Action button
              Padding(
                padding: const EdgeInsets.symmetric(
                  horizontal: 16,
                  vertical: 8,
                ),
                child: owned.when(
                  data: (isOwned) => FilledButton.icon(
                    onPressed: isOwned
                        ? removePackFromMyCollection
                        : addPackToMyCollection,
                    icon: Icon(
                      isOwned ? Symbols.remove_circle : Symbols.add_circle,
                    ),
                    label: Text(isOwned ? 'removePack'.tr() : 'addPack'.tr()),
                    style: FilledButton.styleFrom(
                      padding: const EdgeInsets.symmetric(vertical: 16),
                    ),
                  ),
                  loading: () => const SizedBox(
                    height: 48,
                    child: Center(
                      child: SizedBox(
                        width: 24,
                        height: 24,
                        child: CircularProgressIndicator(strokeWidth: 2),
                      ),
                    ),
                  ),
                  error: (_, _) => OutlinedButton.icon(
                    onPressed: addPackToMyCollection,
                    icon: const Icon(Symbols.add_circle),
                    label: Text('addPack').tr(),
                    style: OutlinedButton.styleFrom(
                      padding: const EdgeInsets.symmetric(vertical: 16),
                    ),
                  ),
                ),
              ),
              Gap(MediaQuery.of(context).padding.bottom + 16),
            ],
          );
        },
        error: (err, _) =>
            Text('Error: $err').textAlignment(TextAlign.center).center(),
        loading: () => const CircularProgressIndicator().center(),
      ),
    );
  }
}

class _PublisherChip extends StatelessWidget {
  final SnPublisher publisher;

  const _PublisherChip({required this.publisher});

  @override
  Widget build(BuildContext context) {
    return ActionChip(
      avatar: publisher.picture != null
          ? ClipRRect(
              borderRadius: BorderRadius.circular(12),
              child: SizedBox(
                width: 24,
                height: 24,
                child: CloudImageWidget(
                  file: publisher.picture!,
                  fit: BoxFit.cover,
                  noBlurhash: true,
                ),
              ),
            )
          : Icon(
              Symbols.account_circle,
              size: 20,
              color: Theme.of(context).colorScheme.onSurfaceVariant,
            ),
      label: Text(
        publisher.nick,
        style: Theme.of(context).textTheme.labelLarge,
      ),
      backgroundColor: Theme.of(context).colorScheme.surfaceContainerHighest,
      side: BorderSide.none,
      onPressed: () {
        context.router.push(PublisherProfileRoute(name: publisher.name));
      },
    );
  }
}

class _MetadataChip extends StatelessWidget {
  final IconData icon;
  final String label;
  final bool isSelectable;

  const _MetadataChip({
    required this.icon,
    required this.label,
    this.isSelectable = false,
  });

  @override
  Widget build(BuildContext context) {
    final theme = Theme.of(context);
    final content = Row(
      mainAxisSize: MainAxisSize.min,
      spacing: 6,
      children: [
        Icon(icon, size: 16, color: theme.colorScheme.onSurfaceVariant),
        isSelectable
            ? SelectableText(
                label,
                style: GoogleFonts.robotoMono(
                  fontSize: 12,
                  color: theme.colorScheme.onSurfaceVariant,
                ),
              )
            : Text(
                label,
                style: GoogleFonts.robotoMono(
                  fontSize: 12,
                  color: theme.colorScheme.onSurfaceVariant,
                ),
              ),
      ],
    );

    return Chip(
      label: content,
      backgroundColor: theme.colorScheme.surfaceContainerLow,
      side: BorderSide.none,
      padding: const EdgeInsets.symmetric(horizontal: 8, vertical: 4),
      visualDensity: VisualDensity.compact,
    );
  }
}
