name: Build Release

on:
  push:
    tags:
      - "*"
  workflow_dispatch:

jobs:
  build-web:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          cache: true
      - run: flutter pub get
      - run: flutter build web --release --dart-define=SENTRY_DSN="${{ secrets.SENTRY_DSN }}"
      - name: Archive production artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-output-web
          path: build/web
  build-exe:
    runs-on: windows-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          cache: true
      - run: flutter pub get
      - run: flutter build windows --dart-define=SENTRY_DSN="${{ secrets.SENTRY_DSN }}"
      - name: Extract Version
        id: extract_version
        run: |
           $pubspec = Get-Content pubspec.yaml -Raw
           if ($pubspec -match 'version:\s*(\d+\.\d+\.\d+)\+(\d+)') {
             $appVersion = $matches[1]
             $buildNumber = $matches[2]
             Write-Host "app_version=$appVersion" >> $env:GITHUB_OUTPUT
             Write-Host "build_number=$buildNumber" >> $env:GITHUB_OUTPUT
           }
      - name: Archive production artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-output-windows
          path: build/windows/x64/runner/Release
      - name: Compile Installer
        uses: Minionguyjpro/Inno-Setup-Action@v1.2.2
        with:
          path: setup.iss
          options: "/DAppVersion=${{ steps.extract_version.outputs.app_version }} /DBuildNumber=${{ steps.extract_version.outputs.build_number }}"
      - name: Archive installer artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-output-windows-installer
          path: Installer/windows-x86_64-setup.exe
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
      - run: |
          sudo apt-get update -y
          sudo apt-get install -y ninja-build libgtk-3-dev
          sudo apt-get install -y libmpv-dev mpv
          sudo apt-get install -y libayatana-appindicator3-dev
          sudo apt-get install -y keybinder-3.0
          sudo apt-get install -y libnotify-dev
          sudo apt-get install -y libgstreamer1.0-dev libgstreamer-plugins-base1.0-dev
          sudo apt-get install -y gstreamer-1.0
          sudo apt-get install -y libsecret-1-dev
      - run: flutter pub get
      - run: flutter build linux --no-tree-shake-icons --dart-define=SENTRY_DSN="${{ secrets.SENTRY_DSN }}"
      - name: Archive production artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-output-linux
          path: build/linux/x64/release/bundle
      - name: Build AppImage
        run: |
          rm -r Solian.AppDir | true
          mkdir Solian.AppDir
          cp -r build/linux/x64/release/bundle/* Solian.AppDir
          cp -r buildtools/appimage_config/* Solian.AppDir
          cp assets/icons/icon-padded.webp Solian.AppDir
          sudo chmod +x buildtools/appimagetool-x86_64.AppImage
          sudo chmod +x Solian.AppDir/AppRun
          ./buildtools/appimagetool-x86_64.AppImage Solian.AppDir
      - name: Archive production artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-output-linux-appimage
          path: "./*.AppImage*"
  upload-to-s3:
    needs: [build-exe, build-linux]
    runs-on: ubuntu-latest
    steps:
      - name: Download Windows installer artifact
        uses: actions/download-artifact@v4
        with:
          name: build-output-windows-installer
          path: ./artifacts/windows
      - name: Download AppImage artifact
        uses: actions/download-artifact@v4
        with:
          name: build-output-linux-appimage
          path: ./artifacts/linux
      - name: Zip Windows installer
        run: |
          cd ./artifacts/windows
          zip -r ../build-output-windows-installer.zip .
      - name: Zip Linux AppImage
        run: |
          cd ./artifacts/linux
          zip -r ../build-output-linux-appimage.zip .
      - name: Upload Windows to R2
        uses: ryand56/r2-upload-action@latest
        with:
          r2-account-id: ${{ secrets.R2_ACCOUNT_ID }}
          r2-access-key-id: ${{ secrets.S3_ACCESS_KEY_ID }}
          r2-secret-access-key: ${{ secrets.S3_SECRET_ACCESS_KEY }}
          r2-bucket: ${{ secrets.S3_BUCKET_NAME }}
          source-dir: ./artifacts/build-output-windows-installer.zip
          destination-dir: solian
      - name: Upload Linux to R2
        uses: ryand56/r2-upload-action@latest
        with:
          r2-account-id: ${{ secrets.R2_ACCOUNT_ID }}
          r2-access-key-id: ${{ secrets.S3_ACCESS_KEY_ID }}
          r2-secret-access-key: ${{ secrets.S3_SECRET_ACCESS_KEY }}
          r2-bucket: ${{ secrets.S3_BUCKET_NAME }}
          source-dir: ./artifacts/build-output-linux-appimage.zip
          destination-dir: solian
